const ENUM_COMMENT_DIALOG_TYPE = {
  NORMAL: 0,
  WARNING: 1,
  URGENT: 2,
};
const ENUM_COMMENT_DIALOG_STATUS = {
  PENDING: 0,
  RESOLVED: 1,
  DELETED: 2,
};

module.exports = {
  ENUM_COMMENT_DIALOG_TYPE,
  ENUM_COMMENT_DIALOG_STATUS,
};
